# Site settings
title: UX Methods
email: andy@andyfitzgeraldconsulting.com
description: >-
  Proof of concept project for the UX Methods ontology and knowledge graph. 
baseurl: "/"
url: "http://uxmethods.org"
github_username: andybywire
ontology_repo: "https://github.com/andybywire/ux-methods-ontology"
kg_repo: "https://github.com/andybywire/ux-methods-kg"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Build settings
markdown: kramdown

# Enable incremental regeneration
# incremental: true

permalink: /:title/

jekyll_rdf:
    path: "_data/UXMethods.owl"
    # path: "_data/UXMethods.ttl"
    baseiri: "https://www.ontology.uxmethods.org/"  # the KG IRI used to generate pages
    default_template: "default-rdf.html"
    restriction: "
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX : <https://www.ontology.uxmethods.org/>
      SELECT ?resourceUri 
      WHERE { 
        {?resourceUri rdf:type :Discipline . }
        UNION
        {?resourceUri rdf:type :Method . }
        UNION
        {?resourceUri rdf:type :Outcome . }
      }
    "
    class_template_mappings:
      "https://www.ontology.uxmethods.org/Discipline": "discipline.html"
      "https://www.ontology.uxmethods.org/Method": "method.html"
      "https://www.ontology.uxmethods.org/Outcome": "outcome.html"
    #instance_template_mappings:

keep_files: 
  - css/style.css # keeps the _site css geing generated by gulp-sass from being blown away on build
  - .git

exclude:
  - README.md
  - gulpfile.js
  - node_modules
  - package.json
  - npm-debug.log
  - package-lock.json

