# Site settings
title: UX Methods
email: andy@andyfitzgeraldconsulting.com
description: >-
  Proof of concept project for the UX Methods ontology and knowledge graph.
baseurl: "/"
url: "http://uxmethods.org"
github_username: andybywire
ontology_repo: "https://github.com/andybywire/ux-methods-ontology"
kg_repo: "https://github.com/andybywire/ux-methods"
repo: "https://github.com/andybywire/ux-methods"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Build settings
markdown: kramdown

# Enable incremental regeneration
# incremental: true

permalink: /:title/

jekyll_rdf:
    # path: "_data/UXMethods.owl"
    remote:
      endpoint: http://localhost:3030/UXM/sparql
    baseiri: "https://www.uxmethods.org/"  # the KG IRI used to generate pages
    default_template: "default-rdf.html"
    restriction: "
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX : <https://www.uxmethods.org/>
      SELECT ?resourceUri
      WHERE {
        {?resourceUri rdf:type :Discipline . }
        UNION
        {?resourceUri rdf:type :Method . }
        UNION
        {?resourceUri rdf:type :Outcome . }
      }
    "
    # Class template mappings fail with an OWL reasoner active at the endpoint.
    class_template_mappings:
        # "https://www.uxmethods.org/Discipline" : "discipline"
        # "https://www.uxmethods.org/Method" : "method"
        # "https://www.uxmethods.org/Insight" : "outcome"
    instance_template_mappings:
        # "https://www.uxmethods.org/Prototyping": "method.html"
        # "https://www.uxmethods.org/InformationArchitecture": "discipline.html"

keep_files:
  - css/style.css # keeps the _site css geing generated by gulp-sass from being blown away on build
  - .git

exclude:
  - README.md
  - gulpfile.js
  - node_modules
  - package.json
  - npm-debug.log
  - package-lock.json
