# Site settings
title: UX Methods
email: andy@andyfitzgeraldconsulting.com
description: >-
  Proof of concept project for the UX Methods ontology and knowledge graph. 
baseurl: "/"
url: "http://uxmethods.app"
github_username: andybywire

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Build settings
markdown: kramdown

permalink: /:title/

jekyll_rdf:
    path: "_data/UXMethods.owl"
    # path: "_data/UXMethods.ttl"
    baseiri: "http://www.semanticweb.org/andyfitzgerald/uxmethods/"  # the KG IRI used to generate pages
    default_template: "default-rdf.html"
    restriction: "
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX : <http://www.semanticweb.org/andyfitzgerald/uxmethods/>
      SELECT ?resourceUri 
      WHERE { 
        {?resourceUri rdf:type :Discipline . }
        UNION
        {?resourceUri rdf:type :Method . }
      }
    "
    class_template_mappings:
      "http://www.semanticweb.org/andyfitzgerald/uxmethods/Discipline": "discipline.html"
      "http://www.semanticweb.org/andyfitzgerald/uxmethods/Method": "method.html"
    #instance_template_mappings:

keep_files: 
  - css/style.css # keeps the _site css geing generated by gulp-sass from being blown away on build

exclude:
  - README.md
  - gulpfile.js
  - node_modules
  - package.json
  - npm-debug.log
  - package-lock.json

